package info.u250.digs;

public class Adagia {
	private static String[] Adagia = new String[]{
		"Make haste slowly",
		"One step at a time",
		"To be in the same boat",
		"To lead one by the nose",
		"A rare bird",
		"Even a child can see it",
		"To have one foot in Charon's boat (To have one foot in the grave)",
		"To walk on tiptoe",
		"One to one",
		"Out of tune",
		"A point in time",
		"I gave as bad as I got (I gave as good as I got)",
		"To call a spade a spade",
		"Hatched from the same egg",
		"Up to both ears (Up to his eyeballs)",
		"As though in a mirror",
		"Think before you start",
		"What's done cannot be undone",
		"Many parasangs ahead (Miles ahead)",
		"We cannot all do everything",
		"Many hands make light work",
		"A living corpse",
		"Where there's life, there's hope",
		"To cut to the quick",
		"Time reveals all things",
		"Golden handcuffs",
		"Crocodile tears",
		"To show the middle finger",
		"You have touched the issue with a needle-point (To have nailed it)",
		"To walk the tightrope",
		"Time tempers grief (Time heals all wounds)",
		"With a fair wind",
		"To dangle the bait",
		"To swallow the hook",
		"The bowels of the earth",
		"From heaven to earth",
		"The dog is worthy of his dinner",
		"To weigh anchor",
		"To grind one's teeth",
		"Nowhere near the mark",
		"Complete the circle",
		"In the land of the blind, the one-eyed man is king",
		"A cough for a fart",
		"No sooner said than done",
		"Neither with bad things nor without them (Women: can't live with 'em, can't live without 'em)",
		"Between a stone and a shrine (Between a rock and a hard place)",
		"Like teaching an old man a new language (Can't teach an old dog new tricks)",
		"A necessary evil",
		"There's many a slip 'twixt cup and lip",
		"To squeeze water out of a stone",
		"To leave no stone unturned",
		"Let the cobbler stick to his last (Stick to your knitting)",
		"God helps those who help themselves",
		"The grass is greener over the fence",
		"The cart before the horse",
		"Dog in the manger",
		"One swallow doesn't make a summer",
		"His heart was in his boots",
		"To sleep on it",
		"To break the ice",
		"Ship-shape",
		"To die of laughing",
		"To have an iron in the fire",
		"To look a gift horse in the mouth",
		"Neither fish nor flesh",
		"Like father, like son",
		"Not worth a snap of the fingers",
		"He blows his own trumpet",
		"To show one's heels",
	};
	public static final String get(){
		return Adagia[Digs.RND.nextInt(Adagia.length)];
	}
}
