package info.u250.digs;

public class Proverb {
	private static String[] Proverb = new String[]{
		"Make haste slowly",
		"One step at a time",
		"To be in the same boat",
		"To lead one by the nose",
		"A rare bird",
		"Even a child can see it",
		"To have one foot in the grave",
		"To walk on tiptoe",
		"One to one",
		"Out of tune",
		"A point in time",
		"I gave as good as I got",
		"To call a spade a spade",
		"Hatched from the same egg",
		"Up to both ears",
		"As though in a mirror",
		"Think before you start",
		"What is done cannot be undone",
		"Many parasangs ahead",
		"We cannot all do everything",
		"Many hands make light work",
		"A living corpse",
		"Where there is life, there is hope",
		"To cut to the quick",
		"Time reveals all things",
		"Golden handcuffs",
		"Crocodile tears",
		"To show the middle finger",
		"To walk the tightrope",
		"Time tempers grief",
		"With a fair wind",
		"To dangle the bait",
		"To swallow the hook",
		"The bowels of the earth",
		"From heaven to earth",
		"The dog is worthy of his dinner",
		"To weigh anchor",
		"To grind one's teeth",
		"Nowhere near the mark",
		"Complete the circle",
		"In the land of the blind, the one-eyed man is king",
		"A cough for a fart",
		"No sooner said than done",
		"Neither with bad things nor without them",
		"Between a stone and a shrine",
		"Like teaching an old man a new language",
		"A necessary evil",
		"There's many a slip 'twixt cup and lip",
		"To squeeze water out of a stone",
		"To leave no stone unturned",
		"Let the cobbler stick to his last",
		"God helps those who help themselves",
		"The grass is greener over the fence",
		"The cart before the horse",
		"Dog in the manger",
		"One swallow doesn't make a summer",
		"His heart was in his boots",
		"To sleep on it",
		"To break the ice",
		"To die of laughing",
		"To have an iron in the fire",
		"To look a gift horse in the mouth",
		"Neither fish nor flesh",
		"Like father, like son",
		"Not worth a snap of the fingers",
		"He blows his own trumpet",
		"To show one's heels",
		"Nice...",
		"..#.&@^*!..",
		"Chiasmus",
		"Where is my love?",
		"Sadly..",
		"Sorrow",
		"Haste makes waste",
		"A stitch in time saves nine",
		"Ignorance is bliss",
		"Mustn't cry over spilled milk.",
		"A bird in the hand is worth two in the bush.",
		"Everyone unto their own.",
		"Well begun is half done.",
		"A little learning is a dangerous thing.",
		"A rolling stone gathers no moss.",
		"Good things come to those who wait.",
		"A poor workman blames his tools.",
		"A dog is a man's best friend.",
		"An apple a day keeps the doctor away.",
		"If the shoe fits, wear it!",
		"Honesty is the best policy",
		"A cat may look at a king",
		"A change is as good as a rest",
		"A dog is a man's best friend",
		"A friend in need is a friend indeed",
		"A golden key can open any door",
		"A good man is hard to find",
		"A house divided against itself cannot stand",
		"A house is not a home",
		"A leopard cannot change its spots",
		"A little knowledge is a dangerous thing",
		"A little learning is a dangerous thing",
		"A little of what you fancy does you good",
		"A miss is as good as a mile",
		"A new broom sweeps clean",
		"A nod's as good as a wink to a blind horse",
		"A penny saved is a penny earned",
		"A person is known by the company he keeps",
		"A picture paints a thousand words",
		"A poor workman always blames his tools",
		"A problem shared is a problem halved",
		"A prophet is not recognized in his own land",
		"A rising tide lifts all boats",
		"A rolling stone gathers no moss",
		"A soft answer turneth away wrath",
		"A stitch in time saves nine",
		"A thing of beauty is a joy forever",
		"A trouble shared is a trouble halved",
		"A volunteer is worth twenty pressed men",
		"A watched pot never boils",
		"A woman's place is in the home",
		"A woman's work is never done",
		"A word to the wise is enough",
		"Absence makes the heart grow fonder",
		"Absolute power corrupts absolutely",
		"Actions speak louder than words",
		"Adversity makes strange bedfellows",
		"After a storm comes a calm",
		"All good things come to he who waits",
		"All good things must come to an end",
		"All is grist that comes to the mill",
		"All publicity is good publicity",
		"All roads lead to Rome",
		"All that glisters is not gold",
		"All that glitters is not gold",
		"All the world loves a lover",
		"All things come to those who wait",
		"All things must pass",
		"All work and no play makes Jack a dull boy",
		"All you need is love",
		"A miss is as good as a mile",
		"An apple a day keeps the doctor away",
		"An army marches on its stomach",
		"An Englishman's home is his castle",
		"Another day, another dollar",
		"Any port in a storm",
		"April showers bring forth May flowers",
		"As thick as thieves",
		"As you sow so shall you reap",
		"Ask no questions and hear no lies",
		"Attack is the best form of defence",
		"Bad money drives out good",
		"Bad news travels fast",
		"Barking dogs seldom bite",
		"Beauty is in the eye of the beholder",
		"Beauty is only skin deep",
		"Beggars should not be choosers",
		"Better late than never",
		"Better safe than sorry",
		"Better the Devil you know than the Devil you don't",
		"Better to light a candle than to curse the darkness",
		"Beware of Greeks bearing gifts",
		"Beware the Ides of March",
		"Big fish eat little fish",
		"Birds of a feather flock together",
		"Blood is thicker than water",
		"Boys will be boys",
		"Brevity is the soul of wit",
		"Business before pleasure",
		"Charity begins at home",
		"Cheats never prosper",
		"Children should be seen and not heard",
		"Cleanliness is next to godliness",
		"Clothes make the man",
		"Cold hands, warm heart",
		"Comparisons are odious",
		"Count your blessings",
		"Cowards may die many times before their death",
		"Crime doesn't pay",
		"Cut your coat to suit your cloth",
		"Dead men tell no tales",
		"Devil take the hindmost",
		"Discretion is the better part of valour",
		"Distance lends enchantment to the view",
		"Do as I say, not as I do",
		"Do as you would be done by",
		"Do unto others as you would have them do to you",
		"Doubt is the beginning not the end of wisdom",
		"East is east, and west is west",
		"Easy come, easy go",
		"Eat, drink and be merry, for tomorrow we die",
		"Empty vessels make the most noise",
		"Enough is as good as a feast",
		"Enough is enough",
		"Even a worm will turn",
		"Every cloud has a silver lining",
		"Every dog has its day",
		"Every Jack has his Jill",
		"Every little helps",
		"Every man has his price",
		"Every picture tells a story",
		"Every stick has two ends",
		"Everyone wants to go to heaven but nobody wants to die",
		"Everything comes to him who waits",
		"Failing to plan is planning to fail",
		"Faint heart never won fair lady",
		"Fair exchange is no robbery",
		"Faith will move mountains",
		"Familiarity breeds contempt",
		"Feed a cold and starve a fever",
		"Fight fire with fire",
		"Finders keepers, losers weepers",
		"Fine words butter no parsnips",
		"First come, first served",
		"First impressions are the most lasting",
		"First things first",
		"Fish always stink from the head down",
		"Fish and guests smell after three days",
		"Flattery will get you nowhere",
		"Fools rush in where angels fear to tread",
		"Forewarned is forearmed",
		"Forgive and forget",
		"Fortune favours the brave",
		"From the sublime to the ridiculous is only one step",
		"Genius is an infinite capacity for taking pains",
		"Give a dog a bad name and hang him",
		"Give a man a fish and you will feed him for a day...",
		"Give a man enough rope and he will hang himself",
		"Give credit where credit is due",
		"God helps those who help themselves",
		"Good fences make good neighbours",
		"Good talk saves the food",
		"Good things come to those who wait",
		"Great minds think alike",
		"Half a loaf is better than no bread",
		"Handsome is as handsome does",
		"Hard cases make bad law",
		"Hard work never did anyone any harm",
		"Haste makes waste",
		"He that goes a-borrowing, goes a-sorrowing",
		"He who can does, he who cannot, teaches",
		"He who hesitates is lost",
		"He who laughs last laughs longest",
		"He who lives by the sword shall die by the sword",
		"He who pays the piper calls the tune",
		"He who sups with the Devil should have a long spoon",
		"Hell hath no fury like a woman scorned",
		"Hindsight is always twenty-twenty",
		"History repeats itself",
		"Home is where the heart is",
		"Honesty is the best policy",
		"Hope springs eternal",
		"Horses for courses",
		"If anything can go wrong, it will",
		"If a job is worth doing it is worth doing well",
		"If at first you don't succeed try, try and try again",
		"If God had meant us to fly he'd have given us wings",
		"If it ain't broke, don't fix it",
		"If life deals you lemons, make lemonade",
		"If the cap fits, wear it",
		"If the shoe fits, wear it",
		"If wishes were horses, beggars would ride",
		"If you lie down with dogs, you will get up with fleas",
		"If you pay peanuts, you get monkeys",
		"If you want a thing done well, do it yourself",
		"Ignorance is bliss",
		"Imitation is the sincerest form of flattery",
		"In for a penny, in for a pound",
		"In the kingdom of the blind the one eyed man is king",
		"In the midst of life we are in death",
		"Into every life a little rain must fall",
		"It ain't over till the fat lady sings",
		"It goes without saying",
		"It is best to be on the safe side",
		"It is better to give than to receive",
		"It is easy to be wise after the event",
		"It never rains but it pours",
		"It takes a thief to catch a thief",
		"It takes all sorts to make a world",
		"It takes one to know one",
		"It takes two to tango",
		"Jack of all trades, master of none",
		"Judge not, that ye be not judged",
		"Keep your chin up",
		"Keep your powder dry",
		"Laugh and the world laughs with you, weep and you weep alone",
		"Laughter is the best medicine",
		"Least said, soonest mended",
		"Less is more",
		"Let bygones be bygones",
		"Let not the sun go down on your wrath",
		"Let sleeping dogs lie",
		"Let the buyer beware",
		"Let the dead bury the dead",
		"Let the punishment fit the crime",
		"Let well alone",
		"Life begins at forty",
		"Life is just a bowl of cherries",
		"Life is what you make it",
		"Life's not all beer and skittles",
		"Lightning never strikes twice in the same place",
		"Like father, like son",
		"Little pitchers have big ears",
		"Little strokes fell great oaks",
		"Little things please little minds",
		"Live for today for tomorrow never comes",
		"Look before you leap",
		"Love is blind",
		"Love makes the world go round",
		"Love thy neighbour as thyself",
		"Love will find a way",
		"Make hay while the sun shines",
		"Make love not war",
		"Man does not live by bread alone",
		"Manners maketh man",
		"Many a little makes a mickle",
		"Many a mickle makes a muckle",
		"Many a true word is spoken in jest",
		"Many hands make light work",
		"March comes in like a lion, and goes out like a lamb",
		"March winds and April showers bring forth May flowers",
		"Marriages are made in heaven",
		"Marry in haste, repent at leisure",
		"Might is right",
		"Mighty oaks from little acorns grow",
		"Misery loves company",
		"Moderation in all things",
		"Monday's child is fair of face, ",
		"Tuesday's child is full of grace,",
		"Wednesday's child is full of woe,",
		"Thursday's child has far to go,",
		"Friday's child is loving and giving,",
		"Saturday's child works hard for its living,",
		"And a child that's born on the Sabbath day",
		"Is fair and wise and good and gay.",
		"Money doesn't grow on trees",
		"Money is the root of all evil",
		"Money isn't everything",
		"Money makes the world go round",
		"Money talks",
		"More haste, less speed",
		"Music has charms to soothe the savage breast",
		"Nature abhors a vacuum",
		"Necessity is the mother of invention",
		"Needs must when the devil drives",
		"Ne'er cast a clout till May be out",
		"Never give a sucker an even break",
		"Never go to bed on an argument",
		"Never judge a book by its cover",
		"Never let the sun go down on your anger",
		"Never look a gift horse in the mouth",
		"Never put off until tomorrow what you can do today",
		"Never speak ill of the dead",
		"Never tell tales out of school",
		"Nine tailors make a man",
		"No man can serve two masters",
		"No man is an island",
		"No names, no pack-drill",
		"No news is good news",
		"No one can make you feel inferior without your consent",
		"No pain, no gain",
		"No rest for the wicked",
		"Nothing is certain but death and taxes",
		"Nothing succeeds like success",
		"Nothing venture, nothing gain",
		"Oil and water don't mix",
		"Old soldiers never die, they just fade away",
		"Once a thief, always a thief",
		"Once bitten, twice shy",
		"One good turn deserves another",
		"One half of the world does not know how the other half lives",
		"One hand washes the other",
		"One man's meat is another man's poison",
		"One might as well be hanged for a sheep as a lamb",
		"One law for the rich and another for the poor",
		"One swallow does not make a summer",
		"One volunteer is worth ten pressed men",
		"One year's seeding makes seven years weeding",
		"Only fools and horses work",
		"Opportunity never knocks twice at any man's door",
		"Out of sight, out of mind",
		"Parsley seed goes nine times to the Devil",
		"Patience is a virtue",
		"Pearls of wisdom",
		"Penny wise and pound foolish",
		"People who live in glass houses shouldn't throw stones",
		"Physician, heal thyself",
		"Possession is nine points of the law",
		"Power corrupts; absolute power corrupts absolutely",
		"Practice makes perfect",
		"Practice what you preach",
		"Prevention is better than cure",
		"Pride goes before a fall",
		"Procrastination is the thief of time",
		"Put your best foot forward",
		"Rain before seven, fine before eleven",
		"Revenge is a dish best served cold",
		"Revenge is sweet",
		"Rob Peter to pay Paul",
		"Rome wasn't built in a day",
		"See no evil, hear no evil, speak no evil",
		"Seeing is believing",
		"Seek and ye shall find",
		"Set a thief to catch a thief",
		"Share and share alike",
		"Shrouds have no pockets",
		"Silence is golden",
		"Slow but sure",
		"Softly, softly, catchee monkey",
		"Spare the rod and spoil the child",
		"Speak as you find",
		"Speak softly and carry a big stick",
		"Still waters run deep",
		"Strike while the iron is hot",
		"Stupid is as stupid does",
		"Success has many fathers, while failure is an orphan",
		"Talk is cheap",
		"Talk of the Devil, and he is bound to appear",
		"Tell the truth and shame the Devil",
		"That which does not kill us makes us stronger",
		"The age of miracles is past",
		"The apple never falls far from the tree",
		"The best defence is a good offence",
		"The best-laid schemes of mice and men gang aft agley",
		"The best things in life are free",
		"The bigger they are, the harder they fall",
		"The bottom line is the bottom line",
		"The boy is father to the man",
		"The bread always falls buttered side down",
		"The child is the father of the man",
		"The cobbler always wears the worst shoes",
		"The course of true love never did run smooth",
		"The customer is always right",
		"The darkest hour is just before the dawn",
		"The devil finds work for idle hands to do",
		"The devil looks after his own",
		"The early bird catches the worm",
		"The end justifies the means",
		"The exception which proves the rule",
		"The female of the species is more deadly than the male",
		"The fruit does not fall far from the tree",
		"The good die young",
		"The grass is always greener on the other side of the fence",
		"The hand that rocks the cradle rules the world",
		"The husband is always the last to know",
		"The labourer is worthy of his hire",
		"The law is an ass",
		"The leopard does not change his spots",
		"The longest journey starts with a single step",
		"The more the merrier",
		"The more things change, the more they stay the same",
		"The only good Indian is a dead Indian",
		"The opera ain't over till the fat lady sings",
		"The pen is mightier than sword",
		"The price of liberty is eternal vigilance",
		"The proof of the pudding is in the eating",
		"The road to hell is paved with good intentions",
		"The shoemaker's son always goes barefoot",
		"The squeaking wheel gets the grease",
		"The truth will out",
		"The way to a man's heart is through his stomach",
		"There are more ways of killing a cat than choking it with cream",
		"There are none so blind as those, that will not see",
		"There are two sides to every question",
		"There but for the grace of God, go I",
		"There's a time and a place for everything",
		"There's an exception to every rule",
		"There's always more fish in the sea",
		"There's honour among thieves",
		"There's many a good tune played on an old fiddle",
		"There's many a slip 'twixt cup and lip",
		"There's more than one way to skin a cat",
		"There's no accounting for tastes",
		"There's no fool like an old fool",
		"There's no place like home",
		"There's no smoke without fire",
		"There's no such thing as a free lunch",
		"There's no such thing as bad publicity",
		"There's no time like the present",
		"There's none so blind as those who will not see",
		"There's none so deaf as those who will not hear",
		"There's nowt so queer as folk",
		"There's one born every minute",
		"There's safety in numbers",
		"They that sow the wind, shall reap the whirlwind",
		"Third time lucky",
		"Those who do not learn from history are doomed to repeat it",
		"Those who live in glass houses shouldn't throw stones",
		"Those who sleep with dogs will rise with fleas",
		"Time and tide wait for no man",
		"Time flies",
		"Time is a great healer",
		"Time is money",
		"Time will tell",
		"To err is human; to forgive divine",
		"To every thing there is a season",
		"To the victor go the spoils",
		"To travel hopefully is a better thing than to arrive",
		"Tomorrow is another day",
		"Tomorrow never comes",
		"Too many cooks spoil the broth",
		"Truth is stranger than fiction",
		"Truth will out",
		"Two blacks don't make a white",
		"Two heads are better than one",
		"Two is company, but three's a crowd",
		"Two wrongs don't make a right",
		"Variety is the spice of life",
		"Virtue is its own reward",
		"Walls have ears",
		"Walnuts and pears you plant for your heirs",
		"Waste not want not",
		"What can't be cured must be endured",
		"What goes up must come down",
		"What you lose on the swings you gain on the roundabouts",
		"What's sauce for the goose is sauce for the gander",
		"When in Rome, do as the Romans do",
		"When the cat's away the mice will play",
		"When the going gets tough, the tough get going",
		"What the eye doesn't see, the heart doesn't grieve over",
		"Where there's a will there's a way",
		"Where there's muck there's brass",
		"While there's life there's hope",
		"Whom the Gods love die young",
		"Why keep a dog and bark yourself?",
		"Women and children first",
		"Wonders will never cease",
		"Work expands so as to fill the time available",
		"Worrying never did anyone any good",
		"You are never too old to learn",
		"You are what you eat",
		"You can have too much of a good thing",
		"You can lead a horse to water, but you can't make it drink",
		"You can't have your cake and eat it",
		"You can't get blood out of a stone",
		"You can't make a silk purse from a sow's ear",
		"You can't make an omelette without breaking eggs",
		"You can't make bricks without straw",
		"You can't run with the hare and hunt with the hounds",
		"You can't teach an old dog new tricks",
		"You can't judge a book by its cover",
		"You can't win them all",
		"You catch more flies with honey than with vinegar",
		"You pays your money and you takes your choice",
		"Youth is wasted on the young",
		"I mean ..",
		"Who save me ..",
		"My girl",
		"Random",
		"XXOO",
		"Survival",
		"Love!",
		"My last chance",
	};
	public static final String get(){
		return Proverb[Digs.RND.nextInt(Proverb.length)];
	}
}
